### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by shmish111** [asakamirai/kazura-queue#1]
Hi, please could you add kazura-queue to stackage, I have a package that uses kazura-queue that I would like to be added to stackage but I cannot until kazura-queue is there.

Instructions are [here](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md).

**Comment by asakamirai** [comment]
@shmish111
Thank you! I'm glad to hear that.
Ok, I will try to add kazura-queue to stackage. But it may take several weeks because of my private schedule.
Do you have a due date?

**Comment by asakamirai** [comment]
@shmish111
I have added kazura-queue to stackage. It can be used from nightly-2018-09-15.

**Comment by shmish111** [comment]
Awesome thanks!
